# Generated by Django 3.1.2 on 2020-11-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('classroom', models.CharField(choices=[('12 IPA 1', '12 IPA 1'), ('12 IPA 2', '12 IPA 2'), ('12 IPA 3', '12 IPA 3'), ('12 IPA 4', '12 IPA 4'), ('12 IPA 5', '12 IPA 5'), ('12 IPA 6', '12 IPA 6'), ('12 IPA 7', '12 IPA 7'), ('12 IPA 8', '12 IPA 8'), ('12 IPS', '12 IPS')], default='12 IPA 1', max_length=10, null=True)),
                ('randomThought', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('instagram', models.CharField(max_length=50, null=True)),
                ('linkedin', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
