# Generated by Django 3.1.2 on 2020-11-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='classroom',
            field=models.CharField(choices=[('12 IPA 1', '12 IPA 1'), ('12 IPA 2', '12 IPA 2'), ('12 IPA 3', '12 IPA 3'), ('12 IPA 4', '12 IPA 4'), ('12 IPA 5', '12 IPA 5'), ('12 IPA 6', '12 IPA 6'), ('12 IPA 7', '12 IPA 7'), ('12 IPA 8', '12 IPA 8'), ('12 IPS', '12 IPS')], default='', max_length=10, null=True),
        ),
    ]
