# Generated by Django 3.1.2 on 2020-11-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0003_auto_20201110_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layouting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupby', models.CharField(choices=[('All', 'All'), ('12 IPA 1', '12 IPA 1'), ('12 IPA 2', '12 IPA 2'), ('12 IPA 3', '12 IPA 3'), ('12 IPA 4', '12 IPA 4'), ('12 IPA 5', '12 IPA 5'), ('12 IPA 6', '12 IPA 6'), ('12 IPA 7', '12 IPA 7'), ('12 IPA 8', '12 IPA 8'), ('12 IPS', '12 IPS')], default='All', max_length=10, null=True)),
                ('sorting', models.CharField(choices=[('Ascending', 'Ascending'), ('Descending', 'Descending')], default='Ascending', max_length=10, null=True)),
            ],
        ),
    ]
