# Generated by Django 3.1.2 on 2020-11-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0004_layouting'),
    ]

    operations = [
        migrations.AddField(
            model_name='layouting',
            name='search',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
